### ISSUE TITLE
"Advanced Micro Devices, Inc." vendor is unsupported.

### ISSUE THREAD

**Issue by inferrna** [codeplaysoftware/computecpp-sdk#9]
```
inferno@hmstr:~$ /usr/local/computecpp/bin/computecpp_info
********************************************************************************

ComputeCpp Info (CE 0.1.1)

********************************************************************************

Toolchain information:

GLIBCXX: 20150426
This version of libstdc++ is supported.

********************************************************************************


Device Info:

Discovered 1 devices matching:
  platform    : <any>
  device type : <any>

--------------------------------------------------------------------------------
Device 0:

  Device is supported                     : NO - Unsupported vendor
  CL_DEVICE_NAME                          : Pitcairn
  CL_DEVICE_VENDOR                        : Advanced Micro Devices, Inc.
  CL_DRIVER_VERSION                       : 1912.5 (VM)
  CL_DEVICE_TYPE                          : CL_DEVICE_TYPE_GPU 
********************************************************************************

********************************************************************************

********************************************************************************
```
My system is Ubuntu 16.04
clinfo output: https://gist.github.com/inferrna/60f2a7a9e8283a6b8edb9a260e55aef0

**Comment by lukeiwanski** [comment]
@inferrna can you confirm that example code isn't working for you?
Unsupported means we do not test ComputeCpp on that device ( OpenCL is a broad platform )
Could you please try to run helloworld application?

**Comment by inferrna** [comment]
```
samples$ nice make test
Running tests...
Test project /media/Compressed/Drivers_bios/src/dev/OpenCL/computecpp-sdk/samples
      Start  1: accessors
 1/19 Test  #1: accessors ........................   Passed    0.87 sec
      Start  2: async_handler
 2/19 Test  #2: async_handler ....................   Passed    0.95 sec
      Start  3: custom_device_selector
 3/19 Test  #3: custom_device_selector ...........   Passed    0.85 sec
      Start  4: example_sycl_application
 4/19 Test  #4: example_sycl_application .........   Passed    1.14 sec
      Start  5: gaussian_blur
 5/19 Test  #5: gaussian_blur ....................   Passed    1.22 sec
      Start  6: hello_world
 6/19 Test  #6: hello_world ......................   Passed    0.95 sec
      Start  7: images
 7/19 Test  #7: images ...........................   Passed    1.03 sec
      Start  8: matrix_multiply_omp
 8/19 Test  #8: matrix_multiply_omp ..............   Passed    0.01 sec
      Start  9: matrix_multiply_sycl
 9/19 Test  #9: matrix_multiply_sycl .............   Passed    0.87 sec
      Start 10: opencl_c_interop
10/19 Test #10: opencl_c_interop .................   Passed    1.02 sec
      Start 11: parallel_for
11/19 Test #11: parallel_for .....................   Passed    0.82 sec
      Start 12: reduction
12/19 Test #12: reduction ........................   Passed    0.94 sec
      Start 13: simple_example_of_vectors
13/19 Test #13: simple_example_of_vectors ........   Passed    0.99 sec
      Start 14: simple_local_barrier
14/19 Test #14: simple_local_barrier .............   Passed    0.92 sec
      Start 15: simple_private_memory
15/19 Test #15: simple_private_memory ............   Passed    0.95 sec
      Start 16: simple_vector_add
16/19 Test #16: simple_vector_add ................   Passed    1.05 sec
      Start 17: smart_pointer
17/19 Test #17: smart_pointer ....................   Passed    1.18 sec
      Start 18: template_functor
18/19 Test #18: template_functor .................   Passed    1.07 sec
      Start 19: using_functors
19/19 Test #19: using_functors ...................   Passed    0.77 sec

100% tests passed, 0 tests failed out of 19

Total Test time (real) =  17.62 sec
```
Even more - all samples are working. But I can't make tensorflow working with OpenCL through computecpp https://github.com/tensorflow/tensorflow/issues/6497
Can this "NO - Unsupported vendor" be a reason?

**Comment by DuncanMcBain** [comment]
Hi @inferrna, thanks for your bug report. The computecpp_info tool attempts to inform the user of how compatible their system is with ComputeCpp, though we want to improve the output of the tool in the near future. Currently, the tool will only output "supported" for a small number of devices, those being devices we've been able to test directly. I'd like it instead to say something like "tested" for those we know work, "supported" for most other devices, and "unsupported" for devices we know definitely don't work (for example, anything from Nvidia, as we cannot target their hardware right now).

All that being said, I don't know why TensorFlow is showing no devices on your system. I'll investigate this and hopefully will be able to update you early next week with some ideas. One last sanity check would be to attempt to run the following code:
```c++
#include <CL/sycl.hpp>
#include <iostream>

int main() {
  auto devices = cl::sycl::device::get_devices();
  std::cout << devices.size() << " devices\n";
  for (auto d : devices)
    std::cout << d.get_info<cl::sycl::info::device::name> << "\n";
}
```
If this outputs your devices, then at least we know that ComputeCpp can see them and returns them in normal code (certainly as it should, since all your tests pass, but I'd like to see what it thinks it's running on!).

**Comment by inferrna** [comment]
Can't compile sample provided, but
```c++
#include <CL/sycl.hpp>
#include <iostream>

int main() {
  auto devices = cl::sycl::device::get_devices();
  std::cout << devices.size() << " devices\n";
  for (auto d : devices)
    std::cout << d.get_info<cl::sycl::info::device::name>() << "\n";
}
```
Was successful compiled with command
`g++ test.cpp -g -std=c++1z -o test -I/usr/local/computecpp/include/ -I/usr/inclide/ -lComputeCpp -L /usr/local/computecpp/lib/`
Unfortunately it gives completely wrong device names. Moreover: it differs each time
(Ran with `LD_PRELOAD=/usr/local/computecpp/lib/libComputeCpp.so ./test > /tmp/testing2.res`)
1st:
```
2 devices
Pitcairn����1����a��J� ��AK�qK�0���K�!i�@��qi��i�P���i�!j�`��qj�1
H�ƕmachine-cp�Q�K۫H�K۫H�B��HP���H1H�ɕmachine-combinerv��HQ��۫H��۫H�B��Hp>��H1
```
2nd:
```
2 devices
Pitcairn1hb	Pb	�a	�a	cAMDq���v�copyImage1DA@@f	����� �������<����������p��
                                                                                                                 9
	0�v���?@unknown@Q?av�+?av�\|w���Ju�@av��@av��}w�0}Ku�A
```

**Comment by DuncanMcBain** [comment]
Hi @inferrna, that's quite bizarre! If I run it I get:
```
3 devices
Cedar
Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
        Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
```
Which is what I'd expect, really. I don't have the same version of the driver as you as my hardware is a little older, so I can't test if that's the difference just yet, but could you tell me what version of GCC you're using? I am compiling with GCC version 4.9. The reason I ask is that we describe ourselves as "C++14 friendly", though we've never tried with the C++17 options. What happens if you try --std=c++14 instead? My coworker with a different card but same driver version cannot reproduce this error either.

**Comment by inferrna** [comment]
I removed fglrx and installed pocl (test compiled with c++14)
```
head /tmp/test_pocl.rest
1 devices
pthread-AMD A8-5500 APU with Radeon(tm) HD Graphics1��(����(������Authenti0pP���M`<2M(3X1���1 devices
pthread-AMD A8-5500 APU with Radeon(tm) HD Graphics1��(����(������Authenti0pP���M`<2M(3X1���1 devices
pthread-AMD A8-5500 APU with Radeon(tm) HD Graphics1��(����(������Authenti0pP���M`<2M(3X1���1 devices
pthread-AMD A8-5500 APU with Radeon(tm) HD Graphics1��(����(������Authenti0pP���M`<2M(3X1���1 devices
```
segfalult was:
```
*** Error in `./test': munmap_chunk(): invalid pointer: 0x0000000000c38d08 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7faecc4b17e5]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x1a8)[0x7faecc4bdae8]
./test[0x400ecb]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7faecc45a830]
./test[0x400d09]
======= Memory map: ========
```
My system is Ubuntu 16.04 with gcc 5.4. I don't know anything about your way to get device name, but it seems very unusual.

**Comment by DuncanMcBain** [comment]
Hi @inferrna, I've managed to reproduce the error. Starting with GCC release 5, the compiler implemented a new ABI as detailed here: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html
We build ComputeCpp with GCC 4.9, as this is the default compiler on our supported system. Generally attempting to link code using the old ABI with the new ABI will cause a linker error to be emitted but there are some corner cases (like this case) where no error will be emitted, seemingly causing problems at runtime.

The tests all work because the CMake code we have in the SDK will automatically add the flag to the compiler that disables the new API when it detects a version of GCC > 5. I'm afraid I can't offer any insight into the errors you are getting from TensorFlow, as this all appears to be working correctly.

I'll try to add some documentation that mentions possible issues with the ABI change.

**Comment by DuncanMcBain** [comment]
Hi @inferrna, did you manage to get any further with this? We've released an updated version of ComputeCpp, and I believe that a few more commits have been made to Tensorflow since you last tried.

**Comment by inferrna** [comment]
Got test code working only with gcc-4.9. With gcc-5 got same errors.
```sh
$ g++-4.9 test.cpp -g -std=c++14 -o test -I/usr/local/computecpp/include/ -I/usr/inclide/ -lComputeCpp -L /usr/local/computecpp/lib/
$ LD_PRELOAD="/usr/local/computecpp/lib/libComputeCpp.so" ./test
3 devices
Pitcairn
AMD A8-5500 APU with Radeon(tm) HD Graphics
pthread-AMD A8-5500 APU with Radeon(tm) HD Graphics
```

TF compiled with OpenCL and gcc-4.9 still shows just cpu device.
```
$ ./bin/computecpp_info 
********************************************************************************

ComputeCpp Info (CE 0.1.2)

********************************************************************************

Toolchain information:

GLIBCXX: 20150426
This version of libstdc++ is supported.

********************************************************************************


Device Info:

Discovered 2 devices matching:
  platform    : <any>
  device type : <any>

--------------------------------------------------------------------------------
Device 0:

  Device is supported                     : UNTESTED - Vendor not tested on this OS
  CL_DEVICE_NAME                          : Pitcairn
  CL_DEVICE_VENDOR                        : Advanced Micro Devices, Inc.
  CL_DRIVER_VERSION                       : 1912.5 (VM)
  CL_DEVICE_TYPE                          : CL_DEVICE_TYPE_GPU 
--------------------------------------------------------------------------------
Device 1:

  Device is supported                     : UNTESTED - Vendor not tested on this OS
  CL_DEVICE_NAME                          : pthread-AMD A8-5500 APU with Radeon(tm) HD Graphics
  CL_DEVICE_VENDOR                        : AuthenticAMD
  CL_DRIVER_VERSION                       : 0.14-pre
  CL_DEVICE_TYPE                          : CL_DEVICE_TYPE_CPU CL_DEVICE_TYPE_DEFAULT
********************************************************************************
```
As variant - would be nice to have some ini file with list of compatible devices where user can enter his own device string.

**Comment by DuncanMcBain** [comment]
Thanks for that, @inferrna. It looks like we have a bug in computecpp_info, I've reported that internally. However, the code in computecpp_info is different to that in ComputeCpp, which is why you're seeing the three devices listed when using get_devices().

We've done a little more digging and it appears the problem was in Eigen. @lukeiwanski has fixed it and updated his version of TensorFlow to use that newer version of Eigen. You can find this here: https://github.com/lukeiwanski/tensorflow-opencl if you'd like to try it out.

Many thanks,
Duncan.

**Comment by DuncanMcBain** [comment]
We managed to do some testing on an APU (admittedly a different model). It looks like it might not work with the default driver installation, though installing and using the amdocl64.so that comes with the AMD APP SDK might have more success (at least, that would match our experience). The Eigen change should stop the APU being filtered out of the list of devices, but whether it will work perfectly or not when you try it I cannot promise.
